### ISSUE TITLE
Replace Email I'D in GGIRHR Website

### ISSUE THREAD

**Issue by HNPavan** [garbhagudi/ggirhr#153]
Dear Avinash

Please replace the email I'D in the GGIRHR website 

Old email I'D - goutham@gggirhr
New email I'D - training@ggirhr.com

**Comment by dbugging404** [comment]
Old Email IDs have been removed. Please Check and and if there are any missed instances, please share a screenshot and the route of the same as a reply to this message and reopen this ticket. It will be corrected.
