### ISSUE TITLE
Creation of new section (tab) under Courses menu

### ISSUE THREAD

**Issue by SudarshanGGD** [garbhagudi/ggirhr#189]
Hi sir,

As we are planning to add new courses, I request you to create a new section (tab) “Micro-Certification” under Courses menu.

Thank you

**Comment by garbhagudi** [comment]
You need to provide all the information. 

New courses added in CMS will not show up in header section automatically. Once you have added all the courses to the CMS. Send me their Names and slug. I will add them to the header tabs. 

Also Don't forget the icons for the courses.
