### ISSUE TITLE
Adding new course to menu

### ISSUE THREAD

**Issue by SudarshanGGD** [garbhagudi/ggirhr#256]
Hi sir please add the below course under the "short Term" menu

Course name: Mastering Egg Pickup

Link: https://www.ggirhr.com/courses/mastering-egg-pickup-oocyte-pickup-ovum-pickup-opu

Thank you

**Comment by snorflux** [comment]
Need Icon for it.

**Comment by snorflux** [comment]
This changes is live now. 

Pls verify the functionality.
