### ISSUE TITLE
GGIRHR website modifications

### ISSUE THREAD

**Issue by SudarshanGGD** [garbhagudi/ggirhr#286]
Hi sir,

Please assist us with the below GGIRHR website modifications:

Create ‘Number of batches per year’ in the duration, qualification and fee section.
Create ‘Number of intake students per batch’ in the duration, qualification and fee section.
Create new course tab for ‘Andrology’

Can we get the updates accomplished by Saturday, December 6, 2024?

Andrology icon is attached. Please check it.

Thank you.
![andrology-01](https://github.com/user-attachments/assets/20204a02-d2ab-48f5-af79-c91ec85821e5)
![andrology-01](https://github.com/user-attachments/assets/18b9c66d-f09f-4df6-a319-19b0a3bf93a9)

**Comment by snorflux** [comment]
Is there any course that is to be added to the andrology course tab or should I create and leave it empty.

**Comment by SudarshanGGD** [comment]
Please add this course under that.

https://www.ggirhr.com/courses/comprehensive-andrology-training-program
